// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG4boUVN9LbFJA_ZQu-GAhM2gfGARaEm8',
    appId: '1:233193101517:android:1f293848c8c29903d27184',
    messagingSenderId: '233193101517',
    projectId: 'markulator-21131',
    storageBucket: 'markulator-21131.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRFYNDrCaG2kkoPDEKwPtT4CCVBUcLsMw',
    appId: '1:233193101517:ios:d57f4bbd630aecd4d27184',
    messagingSenderId: '233193101517',
    projectId: 'markulator-21131',
    storageBucket: 'markulator-21131.firebasestorage.app',
    iosBundleId: 'com.beta.markulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRFYNDrCaG2kkoPDEKwPtT4CCVBUcLsMw',
    appId: '1:233193101517:ios:788f663e50d1d3dcd27184',
    messagingSenderId: '233193101517',
    projectId: 'markulator-21131',
    storageBucket: 'markulator-21131.firebasestorage.app',
    iosBundleId: 'com.example.markulator',
  );
}
